
name: deploy

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run deploy
        env:
          API_KEY: ${{secrets.API_KEY}}
          CLIENT_ID: ${{secrets.CLIENT_ID}}

      - name: Build
	uses: peaceiris/actions-gh-pages@v3
	with:
          deploy_key: ${{secrets.ACTIONS_DEPLOY_KEY}}
          publish_dir: ./build
